/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FreelancersRouteImport } from './routes/freelancers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MessagesIndexRouteImport } from './routes/messages.index'
import { Route as GigsIndexRouteImport } from './routes/gigs.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'
import { Route as GigsNewRouteImport } from './routes/gigs.new'
import { Route as GigsIdRouteImport } from './routes/gigs.$id'
import { Route as DashboardPosterRouteImport } from './routes/dashboard.poster'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelancersRoute = FreelancersRouteImport.update({
  id: '/freelancers',
  path: '/freelancers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: '/messages/',
  path: '/messages/',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIndexRoute = GigsIndexRouteImport.update({
  id: '/gigs/',
  path: '/gigs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsNewRoute = GigsNewRouteImport.update({
  id: '/gigs/new',
  path: '/gigs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GigsIdRoute = GigsIdRouteImport.update({
  id: '/gigs/$id',
  path: '/gigs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPosterRoute = DashboardPosterRouteImport.update({
  id: '/dashboard/poster',
  path: '/dashboard/poster',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/freelancers': typeof FreelancersRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/poster': typeof DashboardPosterRoute
  '/gigs/$id': typeof GigsIdRoute
  '/gigs/new': typeof GigsNewRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/freelancers': typeof FreelancersRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/poster': typeof DashboardPosterRoute
  '/gigs/$id': typeof GigsIdRoute
  '/gigs/new': typeof GigsNewRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/dashboard': typeof DashboardIndexRoute
  '/gigs': typeof GigsIndexRoute
  '/messages': typeof MessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/freelancers': typeof FreelancersRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/poster': typeof DashboardPosterRoute
  '/gigs/$id': typeof GigsIdRoute
  '/gigs/new': typeof GigsNewRoute
  '/profile/$id': typeof ProfileIdRoute
  '/profile/edit': typeof ProfileEditRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/gigs/': typeof GigsIndexRoute
  '/messages/': typeof MessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/freelancers'
    | '/login'
    | '/register'
    | '/dashboard/poster'
    | '/gigs/$id'
    | '/gigs/new'
    | '/profile/$id'
    | '/profile/edit'
    | '/dashboard/'
    | '/gigs/'
    | '/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/freelancers'
    | '/login'
    | '/register'
    | '/dashboard/poster'
    | '/gigs/$id'
    | '/gigs/new'
    | '/profile/$id'
    | '/profile/edit'
    | '/dashboard'
    | '/gigs'
    | '/messages'
  id:
    | '__root__'
    | '/'
    | '/freelancers'
    | '/login'
    | '/register'
    | '/dashboard/poster'
    | '/gigs/$id'
    | '/gigs/new'
    | '/profile/$id'
    | '/profile/edit'
    | '/dashboard/'
    | '/gigs/'
    | '/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FreelancersRoute: typeof FreelancersRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardPosterRoute: typeof DashboardPosterRoute
  GigsIdRoute: typeof GigsIdRoute
  GigsNewRoute: typeof GigsNewRoute
  ProfileIdRoute: typeof ProfileIdRoute
  ProfileEditRoute: typeof ProfileEditRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  GigsIndexRoute: typeof GigsIndexRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelancers': {
      id: '/freelancers'
      path: '/freelancers'
      fullPath: '/freelancers'
      preLoaderRoute: typeof FreelancersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/': {
      id: '/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/': {
      id: '/gigs/'
      path: '/gigs'
      fullPath: '/gigs/'
      preLoaderRoute: typeof GigsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/new': {
      id: '/gigs/new'
      path: '/gigs/new'
      fullPath: '/gigs/new'
      preLoaderRoute: typeof GigsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gigs/$id': {
      id: '/gigs/$id'
      path: '/gigs/$id'
      fullPath: '/gigs/$id'
      preLoaderRoute: typeof GigsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/poster': {
      id: '/dashboard/poster'
      path: '/dashboard/poster'
      fullPath: '/dashboard/poster'
      preLoaderRoute: typeof DashboardPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FreelancersRoute: FreelancersRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardPosterRoute: DashboardPosterRoute,
  GigsIdRoute: GigsIdRoute,
  GigsNewRoute: GigsNewRoute,
  ProfileIdRoute: ProfileIdRoute,
  ProfileEditRoute: ProfileEditRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  GigsIndexRoute: GigsIndexRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
